language: cpp
sudo: required
os: linux
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.4 main
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
      - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
      - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
      - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
      - sourceline: deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main
        key_url: http://apt.llvm.org/llvm-snapshot.gpg.key
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-trusty-7
    packages:
      - g++-4.4
      - g++-4.6
      - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
      - g++-7
      - g++-8
      - clang-3.4
      - clang-3.5
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - clang-4.0
      - clang-5.0
      - clang-6.0
      - clang-7

install:
 - git clone --depth=1 --no-tags -b v1.4.1 https://github.com/google/benchmark.git
 - cat gbench.txt >> benchmark/CMakeLists.txt
 - pushd benchmark
 - mkdir build
 - cd build
 - cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_ENABLE_TESTING=NO -DBENCHMARK_ENABLE_INSTALL=YES
 - cpack -G DEB -D CPACK_PACKAGE_CONTACT=NK -C Release -R 1.4.1
 - make -j3
 - sudo dpkg -i *.deb 
 - popd

script:
 - for v in {4.4,4.6,4.7,4.8,4.9,5,6,7}; do g++-$v --version; CXX=g++-$v ./run.sh; done
 - for v in {3.5,3.6,3.7,3.8,4.0,5.0,6.0,7}; do clang++-$v --version; CXX=clang++-$v ./run.sh; done
